// my-personal-web/src/pages/Experience.tsx
import { useEffect, useState } from 'react';
import { Container, Heading, Table } from 'react-bulma-components';
import services from '../services';
import { showMonthYearOnly } from '../utils/date';

export default function Experience() {
  const [workExperience, setWorkExperience] = useState([]);
  const [eduExperience, setEduExperience] = useState([]);
  const [researchExperience, setResearchExperience] = useState([]);

  useEffect(() => {
    const experiencePromise = services.get(
      'classes/Experience?order=-startDate'
    );
    const eduPromise = services.get('classes/Education?order=-startDate');
    const researchPromise = services.get('classes/Research');
    Promise.allSettled([experiencePromise, eduPromise, researchPromise])
      .then((result) => {
        const experienceData = result[0];
        if (experienceData.status === 'fulfilled') {
          setWorkExperience(experienceData.value.data.results);
        }
        const eduData = result[1];
        if (eduData.status === 'fulfilled') {
          setEduExperience(eduData.value.data.results);
        }
        const researchData = result[2];
        if (researchData.status === 'fulfilled') {
          setResearchExperience(researchData.value.data.results);
        }
      })
      .finally(() => {
        // this.isLoading = false;
      });
  }, []);
  return (
    <Container>
      <Heading>Experience</Heading>
      <Heading subtitle>Work Experience</Heading>
      <Table>
        <thead>
          <tr>
            <th>Job Name</th>
            <th>Company Name</th>
            <th>Description</th>
            <th>Start Date</th>
            <th>End Date</th>
          </tr>
        </thead>
        <tbody>
          {workExperience.map((data: any) => (
            <tr>
              <td>{data.job}</td>
              <td>{data.department}</td>
              <td>{data.description}</td>
              <td>{showMonthYearOnly(data.startDate)}</td>
              <td>{showMonthYearOnly(data.endDate)}</td>
            </tr>
          ))}
        </tbody>
      </Table>
      <Heading subtitle>Education</Heading>
      <Table>
        <thead>
          <tr>
            <th>Degree</th>
            <th>Institution</th>
            <th>Description</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {eduExperience.map((data: any) => (
            <tr>
              <td>{data.degree}</td>
              <td>{data.location}</td>
              <td>{data.description}</td>
              <td>{data.date}</td>
            </tr>
          ))}
        </tbody>
      </Table>
      <Heading subtitle>Research</Heading>
      <Table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Absract</th>
            <th>Paper</th>
            <th>Published Date</th>
          </tr>
        </thead>
        <tbody>
          {researchExperience.map((data: any) => (
            <tr>
              <td>{data.title}</td>
              <td><a href={data.abstract ?? "#"}>{data.abstract}</a></td>
              <td><a href={data.paper ?? "#"}>{data.paper}</a></td>
              <td>{data.publishDate}</td>
            </tr>
          ))}
        </tbody>
      </Table>
    </Container>
  );
}

// src/views/Experience.vue
<template>
  <div>
    <h2 class="title">{{ $t('navigation.experience') }}</h2>
    <b-loading :is-full-page="false" v-model="isLoading">
      <b-icon pack="fas" icon="sync-alt" size="is-large" custom-class="fa-spin">
      </b-icon>
    </b-loading>
    <div class="columns is-multiline">
      <div class="column is-12">
        <h3 class="subtitle">{{ $t('experience.workexperience') }}</h3>
        <b-table :data="workData" detailed detail-key="id">
          <b-table-column field="job" label="Job Name" v-slot="props">
            {{ props.row.job }}
          </b-table-column>
          <b-table-column
            field="department"
            label="Company Name"
            v-slot="props"
          >
            {{ props.row.department }}
          </b-table-column>
          <b-table-column field="startDate" label="Start Date" v-slot="props">
            {{ showMonthYearOnly(props.row.startDate) }}
          </b-table-column>
          <b-table-column field="endDate" label="End Date" v-slot="props">
            <template v-if="props.row.endDate">
              {{ showMonthYearOnly(props.row.endDate) }}
            </template>
            <template v-else> Now </template>
          </b-table-column>
          <template #detail="props">
            <div class="content">
              <p>{{ props.row.description }}</p>
              <b-button
                v-if="props.row.departmentLink"
                outlined
                type="is-info"
                tag="a"
                :href="props.row.departmentLink"
              >
                <span class="icon is-small">
                  <img
                    v-if="props.row.departmentLink"
                    height="16"
                    width="16"
                    alt="logo"
                    :src="`http://www.google.com/s2/favicons?domain=${getDomain(
                      props.row.departmentLink
                    )}`"
                  />
                </span>
                <span>
                  {{ $t('experience.visitcompanypage') }}
                </span>
              </b-button>
            </div>
          </template>
        </b-table>
      </div>
      <div class="column is-12">
        <h3 class="subtitle">{{ $t('experience.education') }}</h3>
        <b-table :data="eduData" detailed detail-key="id">
          <b-table-column field="degree" label="Degree" v-slot="props">
            {{ props.row.degree }}
          </b-table-column>
          <b-table-column field="location" label="Institution" v-slot="props">
            {{ props.row.location }}
          </b-table-column>
          <b-table-column field="date" label="Date" v-slot="props">
            {{ props.row.date }}
          </b-table-column>
          <template #detail="props">
            <div class="content">
              <p>{{ props.row.description }}</p>
              <b-button
                v-if="props.row.departmentLink"
                outlined
                type="is-info"
                tag="a"
                :href="props.row.departmentLink"
              >
                <span class="icon is-small">
                  <img
                    v-if="props.row.departmentLink"
                    height="16"
                    width="16"
                    alt="logo"
                    :src="`http://www.google.com/s2/favicons?domain=${getDomain(
                      props.row.departmentLink
                    )}`"
                  />
                </span>
                <span>
                  {{ $t('experience.visitcompanypage') }}
                </span>
              </b-button>
            </div>
          </template>
        </b-table>
      </div>
      <div class="column is-12">
        <h3 class="subtitle">{{ $t('experience.research_list') }}</h3>
        <b-table :data="researchData">
          <b-table-column field="degree" label="Title" v-slot="props">
            {{ props.row.title }}
          </b-table-column>
          <b-table-column field="asbtract" label="Abstract" v-slot="props">
            <a :href="props.row.abstract">{{ props.row.abstract }}</a>
          </b-table-column>
          <b-table-column field="paper" label="Paper" v-slot="props">
            <a :href="props.row.paper">{{ props.row.paper }}</a>
          </b-table-column>
          <b-table-column field="publishDate" label="Publish Date">
          </b-table-column>
        </b-table>
      </div>
    </div>
  </div>
</template>

<script lang="ts" src="./Experience.ts"></script>
