// src/App.vue
<template>
  <div>
    <my-header></my-header>
    <section class="section">
      <div class="container">
        <router-view/>
      </div>
    </section>
    <my-footer></my-footer>
  </div>
</template>

<script lang="ts">
import MyHeader from '@/components/MyHeader.vue'
import MyFooter from '@/components/MyFooter.vue'

import { Component, Vue } from 'vue-property-decorator'

@Component({
  components: {
    MyHeader,
    MyFooter,
  },
})
export default class App extends Vue {}
</script>

<style lang="scss" src="./App.scss">
</style>

// my-personal-web/src/App.tsx
import React from 'react';
import './App.scss';
import Header from './components/Header';
import { Outlet } from 'react-router-dom';
import { Section } from 'react-bulma-components';
import Footer from './components/Footer';

function App() {
  return (
    <div className="App">
      <Header />
      <Section>
        <Outlet />
      </Section>
      <Footer />
    </div>
  );
}

export default App;
